# Generated by Django 5.1.4 on 2026-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('candidate', models.CharField(db_index=True, max_length=255)),
                ('course', models.CharField(db_index=True, max_length=255)),
                ('schedule', models.CharField(db_index=True, max_length=255)),
                ('enrollments_status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('trainingcenter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('declined_rsn', models.TextField(blank=True, null=True)),
                ('academic_year_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('class_group_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('enrollment_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('enrollment_date', models.DateField(blank=True, null=True)),
                ('application_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('payment_status', models.CharField(db_index=True, default='Pending', max_length=50)),
                ('payment_gateway', models.CharField(blank=True, max_length=255, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_response', models.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EnrollPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('billing_address', models.TextField(blank=True, null=True)),
                ('city', models.BigIntegerField(blank=True, null=True)),
                ('state', models.BigIntegerField(blank=True, null=True)),
                ('country', models.BigIntegerField(blank=True, null=True)),
                ('pincode', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subtotal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('final_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trainingcenter_id', models.CharField(blank=True, max_length=255, null=True)),
                ('candidate_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('currency_type', models.CharField(default='INR', max_length=10)),
                ('enrollment_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('schedule_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('payment_gateway', models.CharField(blank=True, max_length=100, null=True)),
                ('gateway_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_status', models.CharField(db_index=True, default='PENDING', max_length=50)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CandidateSubjectSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('candidate_id', models.CharField(db_index=True, max_length=255)),
                ('application_id', models.CharField(db_index=True, max_length=255)),
                ('academic_year_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('program_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('semester_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('subject_id', models.CharField(db_index=True, max_length=255)),
                ('subject_type', models.CharField(blank=True, max_length=100, null=True)),
                ('selection_status', models.CharField(default='Selected', max_length=50)),
                ('mandatory', models.BooleanField(default=False)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('application_id', 'subject_id'), name='unique_admission_subject_selection')],
            },
        ),
    ]
