# Generated by Django 5.1.4 on 2026-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidatesubjectselection',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='candidatesubjectselection',
            name='unique_admission_subject_selection',
        ),
    ]
