# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_candidatesubjectselection_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollments',
            old_name='trainingcenter_id',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='enrollpayment',
            old_name='trainingcenter_id',
            new_name='college_id',
        ),
    ]
