# Generated by Django 5.1.4 on 2026-08-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0003_rename_trainingcenter_id_enrollments_college_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatesubjectselection',
            old_name='program_id',
            new_name='course_id',
        ),
    ]
