# Generated by Django 5.1.4 on 2026-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('course', models.CharField(db_index=True, max_length=255)),
                ('college', models.CharField(blank=True, max_length=255, null=True)),
                ('schedule', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('class_group_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('candidate_feedbackform', models.TextField(blank=True, null=True)),
                ('faculty_feedbackform', models.TextField(blank=True, null=True)),
                ('college_feedbackform', models.TextField(blank=True, null=True)),
                ('send_via', models.CharField(blank=True, max_length=50, null=True)),
                ('certification_choice', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('add_note', models.TextField(blank=True)),
                ('category_name', models.CharField(max_length=255)),
                ('rating_type', models.CharField(max_length=50)),
                ('question', models.TextField(blank=True, null=True)),
                ('upload_img', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('feedback_form_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('question', models.TextField(blank=True, null=True)),
                ('upload_img', models.TextField(blank=True, null=True)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('feedback_activation_id', models.BigIntegerField(db_index=True)),
                ('feedback_question_id', models.BigIntegerField(db_index=True)),
                ('respondent_type', models.CharField(db_index=True, max_length=30)),
                ('respondent_id', models.CharField(db_index=True, max_length=255)),
                ('rating_value', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('response_text', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedbackSubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('parent_feedback_category', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
