# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedbackactivation',
            old_name='training_center',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='feedbackactivation',
            old_name='training_center_feedbackform',
            new_name='college_feedbackform',
        ),
    ]
