# Generated by Django 5.1.4 on 2026-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classgroup',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='classgroup',
            name='uniq_academic_class_group',
        ),
        migrations.RemoveConstraint(
            model_name='program',
            name='uniq_department_program',
        ),
        migrations.RemoveConstraint(
            model_name='semester',
            name='uniq_program_semester',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='program_id',
        ),
    ]
