# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0002_alter_classgroup_options_alter_program_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='training_center',
            new_name='college',
        ),
        migrations.AddField(
            model_name='department',
            name='college_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
