# Generated by Django 5.1.4 on 2026-08-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_rename_training_center_branch_college_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classgroup',
            old_name='academic_year_id',
            new_name='course_id',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='batch_name',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='class_teacher_id',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='classgroup',
            name='semester_id',
        ),
        migrations.AddField(
            model_name='classgroup',
            name='og_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='semester_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
