# Generated by Django 5.1.4 on 2026-08-18 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0004_rename_academic_year_id_classgroup_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sub_category',
            old_name='category_name',
            new_name='category_id',
        ),
    ]
