# Generated by Django 5.1.4 on 2026-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_rename_category_name_sub_category_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='program_id',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
    ]
