# Generated by Django 5.1.4 on 2026-08-24 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0006_semester_program_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classgroup',
            name='course_id',
        ),
    ]
