# Generated by Django 5.1.4 on 2026-08-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0007_remove_classgroup_course_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='program_id',
        ),
    ]
