# Generated by Django 5.1.4 on 2026-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facultyattendance',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='lectureattendancedetail',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='facultyattendance',
            name='uniq_faculty_daily_attendance',
        ),
        migrations.RemoveConstraint(
            model_name='lectureattendancedetail',
            name='uniq_student_lecture_attendance',
        ),
    ]
