# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_facultyattendance_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidateattendance',
            old_name='training_center_id',
            new_name='college_id',
        ),
    ]
