# Generated by Django 5.1.4 on 2026-09-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_seed_leave_master_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('holiday_date', models.DateField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'attendance_holiday',
                'ordering': ('holiday_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='facultyattendance',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='facultyattendance',
            unique_together={('faculty_id', 'attendance_date')},
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='day_status',
            field=models.CharField(db_index=True, default='PRESENT', max_length=20),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='is_early',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facultyattendance',
            name='total_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.RemoveField(
            model_name='facultyattendance',
            name='attendance_status',
        ),
    ]
