# Generated by Django 5.1.4 on 2026-08-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_training_center_id_candidateattendance_college_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyattendance',
            name='attendance_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lectureattendancesession',
            name='attendance_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
