# Generated by Django 5.1.4 on 2026-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('academic_year_id', models.BigIntegerField(db_index=True)),
                ('class_group_id', models.BigIntegerField(db_index=True)),
                ('course_id', models.BigIntegerField(db_index=True)),
                ('faculty_id', models.CharField(db_index=True, max_length=255)),
                ('timetable_slot_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('lecture_date', models.DateField(db_index=True)),
                ('start_time', models.CharField(blank=True, max_length=250, null=True)),
                ('end_time', models.CharField(blank=True, max_length=250, null=True)),
                ('topic', models.CharField(max_length=500)),
                ('teaching_method', models.CharField(blank=True, max_length=150, null=True)),
                ('lecture_status', models.CharField(db_index=True, default='SCHEDULED', max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RescheduleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('schedule_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('old_start_date', models.DateField(blank=True, null=True)),
                ('old_end_date', models.DateField(blank=True, null=True)),
                ('old_start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('old_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('new_start_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('new_start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('new_end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('branch_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('faculty_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('faculty2_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('academic_year_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('class_group_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('start_time', models.CharField(blank=True, max_length=255, null=True)),
                ('end_time', models.CharField(blank=True, max_length=255, null=True)),
                ('max_capacity', models.PositiveIntegerField(default=0)),
                ('mode', models.CharField(blank=True, max_length=50, null=True)),
                ('schedulename', models.CharField(blank=True, max_length=255, null=True)),
                ('action_status', models.CharField(db_index=True, default='Approved', max_length=50)),
                ('decline_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleCollegeMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('schedule_id', models.BigIntegerField(db_index=True)),
                ('college_id', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScheduleCourseMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('schedule_id', models.BigIntegerField(db_index=True)),
                ('course_id', models.BigIntegerField(db_index=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('academic_year_id', models.BigIntegerField(db_index=True)),
                ('class_group_id', models.BigIntegerField(db_index=True)),
                ('template_name', models.CharField(max_length=150)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimetableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('timetable_template_id', models.BigIntegerField(db_index=True)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('period_number', models.PositiveSmallIntegerField()),
                ('start_time', models.CharField(blank=True, max_length=250, null=True)),
                ('end_time', models.CharField(blank=True, max_length=250, null=True)),
                ('course_id', models.BigIntegerField(db_index=True)),
                ('faculty_id', models.CharField(db_index=True, max_length=255)),
                ('room_number', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_for', models.CharField(blank=True, default='lecture', max_length=50, null=True)),
                ('lecture_type', models.CharField(default='THEORY', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('timetable_template_id', 'day_of_week', 'period_number'), name='uniq_timetable_period')],
            },
        ),
    ]
