# Generated by Django 5.1.4 on 2026-08-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_status',
            field=models.BooleanField(default=True),
        ),
    ]
