# Generated by Django 5.1.4 on 2026-08-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='sub_category_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
