# Generated by Django 5.1.4 on 2026-08-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courseclass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='og_approved',
        ),
        migrations.RemoveField(
            model_name='course',
            name='og_approvedby',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ptc_approved',
        ),
        migrations.RemoveField(
            model_name='course',
            name='ptc_approvedby',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_lectures',
        ),
        migrations.RemoveField(
            model_name='course',
            name='total_practicals',
        ),
    ]
