# Generated by Django 5.1.4 on 2026-08-17 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_remove_course_og_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='department_id',
            new_name='course_id',
        ),
        migrations.AddField(
            model_name='subject',
            name='og_code',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
