# Generated by Django 5.1.4 on 2026-08-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_rename_department_id_subject_course_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
