# Generated by Django 5.1.4 on 2026-08-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_alter_course_course_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessonplan',
            name='program_id',
        ),
    ]
