# Generated by Django 5.1.4 on 2026-08-24 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_remove_lessonplan_program_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSubjectAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('class_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('academic_year_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('semester_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('subject_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('student_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
