# Generated by Django 5.1.4 on 2026-08-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_studentsubjectallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='semister_count',
            new_name='semester_count',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='semister_per_year',
            new_name='semester_per_year',
        ),
        migrations.RenameField(
            model_name='coursematerial',
            old_name='semister_id',
            new_name='semester_id',
        ),
        migrations.RenameField(
            model_name='coursesubjects',
            old_name='semister_no',
            new_name='semester_no',
        ),
    ]
