# Generated by Django 5.1.4 on 2026-08-24 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_rename_semister_count_course_semester_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPlanExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('lesson_plan_id', models.BigIntegerField(db_index=True)),
                ('lesson_plan_unit_id', models.BigIntegerField(db_index=True)),
                ('attendance_session_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('executed_on', models.DateField(db_index=True)),
                ('lecture_count', models.DecimalField(decimal_places=1, default=1, max_digits=4)),
                ('topics_covered', models.TextField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('completed_by', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='lessonplan',
            name='is_active',
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='subject_id',
            field=models.BigIntegerField(db_index=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplanunit',
            name='co_mapping',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanunit',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanunit',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lessonplanunit',
            name='teaching_method',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonplanunit',
            name='completed_lectures',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
