# Generated by Django 5.1.4 on 2026-08-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('question_id', models.BigIntegerField(db_index=True, null=True)),
                ('duplicate_of', models.JSONField(blank=True, default=list)),
                ('course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('module_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('severity_level', models.CharField(max_length=50, null=True)),
                ('type_of_question', models.CharField(max_length=50, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('course', models.JSONField(blank=True, default=list)),
                ('module', models.JSONField(blank=True, default=list)),
                ('type_of_question', models.CharField(max_length=50, null=True)),
                ('question_text', models.TextField(null=True)),
                ('correct_option', models.BigIntegerField(null=True)),
                ('time_to_solve', models.PositiveIntegerField(default=0)),
                ('marks', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('difficulty_level', models.CharField(db_index=True, max_length=50, null=True)),
                ('tags', models.TextField(null=True)),
                ('note', models.TextField(null=True)),
                ('is_archive', models.BooleanField(default=False)),
                ('archive_reason', models.TextField(null=True)),
                ('is_duplicate', models.BooleanField(default=False)),
                ('tc_id', models.CharField(max_length=255, null=True)),
                ('course_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('module_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('question_id', models.BigIntegerField(db_index=True, null=True)),
                ('image', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('question_id', models.BigIntegerField(db_index=True, null=True)),
                ('actionby', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('is_like', models.BooleanField(default=False)),
                ('is_dislike', models.BooleanField(default=False)),
                ('dislike_reason', models.TextField(null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('question_id', models.BigIntegerField(db_index=True, null=True)),
                ('option', models.PositiveIntegerField(null=True)),
                ('option_answer', models.TextField(null=True)),
                ('option_image', models.TextField(null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('question_id', 'option'), name='uniq_question_option_number')],
            },
        ),
    ]
