# Generated by Django 5.1.4 on 2026-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionoption',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='questionoption',
            name='uniq_question_option_number',
        ),
    ]
