# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_alter_questionoption_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='module',
            new_name='subject',
        ),
    ]
