# Generated by Django 5.1.4 on 2026-08-24 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_rename_module_question_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='duplicatequestion',
            old_name='module_id',
            new_name='subject_id',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='module_id',
            new_name='subject_id',
        ),
    ]
