# Generated by Django 5.1.4 on 2026-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examcandidateresult',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='examcandidateresult',
            name='uniq_exam_schedule_candidate_result',
        ),
    ]
