# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_examcandidateresult_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examset',
            old_name='training_center',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='mockexamquestionset',
            old_name='training_center',
            new_name='college',
        ),
        migrations.RenameField(
            model_name='scheduleexam',
            old_name='training_center',
            new_name='college',
        ),
    ]
