# Generated by Django 5.1.4 on 2026-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('ticket', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('categoryId', models.CharField(blank=True, max_length=255, null=True)),
                ('departmentId', models.CharField(blank=True, max_length=255, null=True)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media/activity/attachment/')),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('requestername', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('raisedate', models.DateField(auto_now_add=True)),
                ('raiseby', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('ticketid', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('IPAddress', models.GenericIPAddressField(blank=True, null=True)),
                ('isduplicate', models.BooleanField(default=False)),
                ('parentticketid', models.CharField(blank=True, max_length=255, null=True)),
                ('parent_college_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_college_id', models.CharField(blank=True, max_length=255, null=True)),
                ('og_code', models.CharField(blank=True, max_length=150, null=True)),
                ('requester_type', models.CharField(blank=True, db_index=True, max_length=30, null=True)),
                ('related_student_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('department_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('ticket', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='media/activity/attachment/')),
                ('isread', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketAssign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('ticket', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TicketAttachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('ticket', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachment/')),
                ('comment', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
