# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='parent_training_center_id',
            new_name='parent_college_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='sub_training_center_id',
            new_name='sub_college_id',
        ),
    ]
