# Generated by Django 5.1.4 on 2026-09-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionEligibilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('academic_year_id', models.BigIntegerField(db_index=True)),
                ('course_id', models.BigIntegerField(db_index=True)),
                ('rule_name', models.CharField(max_length=255)),
                ('minimum_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('maximum_age', models.PositiveIntegerField(blank=True, null=True)),
                ('qualification_id', models.BigIntegerField(blank=True, null=True)),
                ('required_documents', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralEligibilityDepartmentRankCombinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('general_eligibility_rule_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('departments', models.BigIntegerField(blank=True, null=True)),
                ('ranks', models.BigIntegerField(blank=True, null=True)),
                ('minimum_age', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralEligibilityEducationalQualifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('general_eligibility_rule_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('educational_qualification_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralEligibilityMandatoryDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('general_eligibility_rule_id', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('document_id', models.BigIntegerField(blank=True, null=True)),
                ('document_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneralEligibilityRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('country_id', models.BigIntegerField(blank=True, null=True)),
                ('country_name', models.CharField(blank=True, max_length=255, null=True)),
                ('rule_no', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
    ]
