# Generated by Django 5.1.4 on 2026-08-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissioneligibilityrule',
            old_name='program_id',
            new_name='course_id',
        ),
    ]
