# Generated by Django 5.1.4 on 2026-08-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parentstudentmapping',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='parentstudentmapping',
            name='uniq_parent_student_relation',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='coc',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='next_vessel',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='program_id',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='seaman_book_number',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='vessel_name',
        ),
    ]
