# Generated by Django 5.1.4 on 2026-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='role_code',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
