# Generated by Django 5.1.4 on 2026-08-24 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_alter_parentstudentmapping_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissionapplication',
            old_name='program_id',
            new_name='course_id',
        ),
    ]
