# Generated by Django 5.1.4 on 2026-08-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_rename_program_id_admissionapplication_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='og_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
