# Generated by Django 5.1.4 on 2026-08-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_admissionapplication_og_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='course_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
