# Generated by Django 5.1.4 on 2026-08-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rolemodulepermission',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='rolemodulepermission',
            name='uniq_role_module_permission',
        ),
    ]
