# Generated by Django 5.1.4 on 2026-08-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='is_organisation',
            field=models.BooleanField(default=False),
        ),
    ]
