# Generated by Django 5.1.4 on 2026-08-11 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0002_useradmin_is_organisation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainingCenterCourses',
            new_name='CollegeCourses',
        ),
    ]
