# Generated by Django 5.1.4 on 2026-08-12 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0003_rename_trainingcentercourses_collegecourses'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permissions',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='permissions',
            name='uniq_role_menu_permission',
        ),
    ]
