# Generated by Django 5.1.4 on 2026-08-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0004_alter_permissions_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collegecourses',
            old_name='training_center_id',
            new_name='college_id',
        ),
        migrations.RenameField(
            model_name='useradmin',
            old_name='is_parent_training_center',
            new_name='is_parent_college',
        ),
        migrations.RenameField(
            model_name='useradmin',
            old_name='parent_training_center',
            new_name='parent_college',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='preferred_teaching_mode',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='Religion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='account_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='adhar_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='bank_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='pan_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
