# Generated by Django 5.1.4 on 2026-08-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0005_rename_training_center_id_collegecourses_college_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='college_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
