# Generated by Django 5.1.4 on 2026-09-09 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0005_designation_city_state_master_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(null=True)),
                ('createdBy', models.CharField(blank=True, max_length=255, null=True)),
                ('updatedBy', models.CharField(blank=True, max_length=255, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True)),
                ('course_id', models.IntegerField(db_index=True)),
                ('college_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ('-createdAt',),
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='TrainingCenterCourses',
        ),
        migrations.AlterModelOptions(
            name='permissions',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RemoveConstraint(
            model_name='permissions',
            name='uniq_role_menu_permission',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='accreditation_number',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='og_id',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='parent_training_center',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='preferred_teaching_mode',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='staff_id',
        ),
        migrations.AddField(
            model_name='useradmin',
            name='blood_group',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='caste',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='is_organisation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='is_parent_college',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='marital_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='parent_college',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='qualification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useradmin',
            name='religion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useradmin',
            name='college_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
