# Generated by Django 5.1.4 on 2026-08-24 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminauth', '0006_alter_useradmin_college_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useradmin',
            old_name='Religion',
            new_name='religion',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='accreditation_number',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='current_status',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='og_id',
        ),
        migrations.RemoveField(
            model_name='useradmin',
            name='staff_id',
        ),
    ]
